### ISSUE TITLE
FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream

### ISSUE THREAD

**Issue by zar3bski** [docker-library/drupal#167]
Am I the only one struggling using `drupal:8.8.1-fpm-alpine` with Nginx? Either I missed an obvious part about how FPM works or there is some **ENV VARs** to be tuned with this image: 

```java
upstream drupal_user_container {
        server user_asmodius_drupal:9000;
    }

server {
    listen 80;
    server_name user.eu; 
    root /var/www/html/user;

        location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    location ~ ^/sites/.*/private/ {
        return 403;
    }

    location / {
        try_files $uri /index.php?$query_string;
    }

    location @rewrite {
        rewrite ^/(.*)$ /index.php?q=$1;
    }

    location ~ /vendor/.*\.php$ {
        deny all;
        return 404;
    }

    location ~ '\.php$|^/update.php' {
        fastcgi_split_path_info ^(.+?\.php)(|/.*)$;
        include fastcgi_params;
        fastcgi_param HTTP_PROXY "";
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name; # HERE IS PROBABLY THE ISSUE
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_intercept_errors on;

        fastcgi_pass drupal_user_container; 
    }

    location ~ ^/sites/.*/files/styles/ { # For Drupal >= 7
        try_files $uri @rewrite;
    }

    # Handle private files through Drupal.
    location ~ ^/system/files/ { # For Drupal >= 7
        try_files $uri /index.php?$query_string;
    }

    # prevent hotlinking
    location ~ ^/sites/.*/files/ {
        if ($invalid_referer) {
          return 403;
        }
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        if ($invalid_referer) {
          return 403;
        }
        expires max;
        log_not_found off;
    }
```
Nothing quite fancy with this docker compose, I just mount `/var/www/html` so that Nginx could serve static files

```yaml

  nginx: 
    container_name: ${SERVER_NAME}_nginx
    restart: always
    networks: 
      - monitoring
      - web
    image: nginx:1.17.5-alpine
    entrypoint: /entrypoint.sh
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - user_www:/var/www/html/user:ro

  drupal:
    restart: always
    container_name: "user_${SERVER_NAME}_drupal"
    image: drupal:8.8.1-fpm-alpine
    networks:
      - web
      - backend
    volumes:
      - user_www:/var/www/html
```

Here is the error: 

```
 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.128.1, server: user.eu, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.144.4:9000", host: "user.eu"
```
