### ISSUE TITLE
Drupal 7 + docker installation: problems with www-data access to volume

### ISSUE THREAD

**Issue by vvmspace** [docker-library/drupal#172]
I have folder "sites"

My docker-compose:

```
version: '3.1'
services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=soomepathword
    expose:
      - "3306"
    volumes:
      - ./mysql:/var/lib/mysql
  web:
    image: drupal:7.69
    volumes: 
      - ./sites:/var/www/html/sites
    ports:
      - "80:80"
    links:
      - db
```
I have problem in installation process:

```
The directory sites/default/files  does not exist. An automated attempt to create this directory failed,  possibly due to a permissions problem. To proceed with the installation,  either create the directory and modify its permissions manually or  ensure that the installer has the permissions to create it  automatically. For more information, see INSTALL.txt or the online handbook.

```
