### ISSUE TITLE
Docker compose volumes not working.

### ISSUE THREAD

**Issue by steveiliop56** [docker-library/drupal#245]
Hello I am trying to install drupal with a docker-compose file but it says it cant create the files and I get forbidden every time I try to access it. 

```Yaml
version: "3.7"
services:
  drupal:
    image: drupal:php8.2-apache
    restart: unless-stopped
    container_name: drupal
    ports:
      - 80:80
    volumes:
      - /home/steve/drupal/data:/opt/drupal
```
